apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: damselfly-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: damselfly-go 
  name: damselfly-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: damselfly-go 
